import { useState } from 'react';
import { useAuth } from '../AuthContext';
import { Copy, Activity, Download, Settings, RefreshCw, FileKey } from 'lucide-react';

export default function Dashboard() {
  const { user } = useAuth();
  const [copied, setCopied] = useState(false);
  const [loadingCode, setLoadingCode] = useState(false);

  // Safely grab token from localStorage
  const oidcToken = localStorage.getItem('oidc_token') || user?.token || 'no_token_found';

  const copyToClipboard = () => {
    navigator.clipboard.writeText(oidcToken);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const simulatedGenerateCode = () => {
    setLoadingCode(true);
    setTimeout(() => setLoadingCode(false), 1000);
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <div>
          <h1>Integration Dashboard</h1>
          <p style={{ color: 'var(--text-muted)' }}>Configure and manage Genesys Cloud Web Messaging</p>
        </div>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button className="btn btn-primary" onClick={simulatedGenerateCode}>
            <RefreshCw size={18} className={loadingCode ? "animate-spin" : ""} />
            Sync Provider
          </button>
          <button className="btn btn-outline">
            <Settings size={18} />
            Settings
          </button>
        </div>
      </div>

      <div className="stat-grid">
        <div className="glass-panel stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span className="stat-card-title">User State</span>
            <Activity size={20} color="var(--accent-color)" />
          </div>
          <div>
            <div className="stat-card-value">{user?.name}</div>
            <div className="connection-status">
              <div className="status-dot"></div>
              <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Authenticated (Mock OIDC)</span>
            </div>
          </div>
        </div>

        <div className="glass-panel stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span className="stat-card-title">Token Explorer</span>
            <FileKey size={20} color="var(--accent-color)" />
          </div>
          <div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
              Current Auth Token
            </div>
            <div 
              style={{ 
                background: 'rgba(13, 17, 23, 0.8)', 
                padding: '0.75rem', 
                borderRadius: '8px', 
                border: '1px solid var(--border-color)',
                fontFamily: 'monospace',
                fontSize: '0.85rem',
                color: 'var(--accent-color)',
                wordBreak: 'break-all',
                position: 'relative'
              }}
            >
              {oidcToken.substring(0, 32)}...
              <button 
                onClick={copyToClipboard}
                style={{ 
                  position: 'absolute', 
                  right: '0.5rem', 
                  top: '50%', 
                  transform: 'translateY(-50%)',
                  background: 'transparent',
                  border: 'none',
                  color: copied ? '#3fb950' : 'var(--text-muted)',
                  cursor: 'pointer'
                }}
                title="Copy token"
              >
                <Copy size={16} />
              </button>
            </div>
            {copied && <p style={{ fontSize: '0.75rem', color: '#3fb950', marginTop: '0.5rem' }}>Copied to clipboard!</p>}
          </div>
        </div>
      </div>

      <div className="glass-panel" style={{ padding: '2rem' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '1rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' }}>
          Genesys Web Messaging Integration
        </h2>
        
        <p style={{ color: 'var(--text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
          Use the snippet below to initialize Genesys Cloud Web Messaging. Ensure you pass the <code style={{ color: 'var(--accent-color)', background: 'rgba(88,166,255,0.1)', padding: '2px 4px', borderRadius: '4px' }}>authCode</code> or token generated by your OIDC provider to trigger step-up authentication. 
          <br /><br />
          <em>Note: Full SSO has been omitted as instructed since it requires creating an OAuth configuration in your Genesys Cloud deployment.</em>
        </p>

        <div style={{ position: 'relative' }}>
          <pre 
            style={{ 
              background: '#0d1117', 
              border: '1px solid var(--border-color)', 
              borderRadius: '8px', 
              padding: '1.5rem', 
              overflowX: 'auto',
              color: '#e6edf3',
              fontSize: '0.9rem',
              lineHeight: '1.5',
              fontFamily: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace"
            }}
          >
{`// 1. Load the Genesys Cloud snippet
(function(g, e, n, es, ys) {
  g['_genesysJs'] = e;
  g[e] = g[e] || function() {
    (g[e].q = g[e].q || []).push(arguments)
  };
  g[e].t = 1 * new Date();
  g[e].c = es;
  ys = document.createElement('script'); ys.async = 1; ys.src = n; ys.charset = 'utf-8'; document.head.appendChild(ys);
})(window, 'Genesys', 'https://apps.mypurecloud.com/genesys-bootstrap/genesys.min.js', {
  environment: 'use1',
  deploymentId: 'YOUR_DEPLOYMENT_ID'
});

// 2. Perform Step-Up Authentication using OAuth integration
Genesys('command', 'Auth.setJwt', {
  jwt: '${oidcToken}'
});

// Alternative: If using auth code flow directly in web messaging popup
// You can pass the authCode when requested by the plugin
Genesys("publish", "Auth.ready", {});`}
          </pre>
          <button 
            className="btn btn-outline"
            style={{ 
              position: 'absolute', 
              top: '1rem', 
              right: '1rem',
              padding: '0.5rem',
              background: 'var(--surface-color)'
            }}
            onClick={() => {
              const code = document.querySelector('pre')?.innerText;
              if (code) navigator.clipboard.writeText(code);
            }}
          >
            <Download size={16} /> Copy Code
          </button>
        </div>
      </div>
    </div>
  );
}
